local layout = {
  "LinearLayout",
  layout_width = "fill",
  layout_height = "fill",
  orientation = "vertical",
  backgroundColor = "#F5F5F5",
  {
    "ScrollView",
    layout_width = "fill",
    layout_height = "fill",
    fillViewport = true,
    {
      "LinearLayout",
      layout_width = "fill",
      layout_height = "wrap",
      orientation = "vertical",
      padding = "16dp",
      {
        "CardView",
        layout_width = "fill",
        layout_height = "wrap",
        layout_marginBottom = "16dp",
        cardElevation = "4dp",
        radius = "8dp",
        {
          "LinearLayout",
          layout_width = "fill",
          layout_height = "wrap",
          orientation = "vertical",
          padding = "16dp",
          {
            "TextView",
            text = "Lua 混淆器",
            textSize = "20sp",
            textColor = "#212121",
            textStyle = "bold",
            layout_marginBottom = "8dp",
          },
          {
            "TextView",
            text = "支持 Androlua+ 语法与虚拟化混淆",
            textSize = "14sp",
            textColor = "#757575",
            layout_marginBottom = "12dp",
          },
          {
            "EditText",
            id = "edit_path",
            hint = "输入 Lua 文件路径 (如 /sdcard/1.lua)",
            layout_width = "fill",
            textSize = "14sp",
            singleLine = true,
          },
        },
      },
      {
        "CardView",
        layout_width = "fill",
        layout_height = "wrap",
        layout_marginBottom = "16dp",
        cardElevation = "2dp",
        radius = "8dp",
        {
          "LinearLayout",
          layout_width = "fill",
          layout_height = "wrap",
          orientation = "vertical",
          padding = "16dp",
          {
            "TextView",
            text = "选项配置",
            textSize = "16sp",
            textColor = "#212121",
            layout_marginBottom = "12dp",
          },
          {
            "CheckBox",
            id = "cb_int_enc",
            text = "加密整数",
            checked = true,
          },
          {
            "TextView",
            text = "整数加密处理率",
            textSize = "12sp",
            layout_marginTop = "8dp",
          },
          {
            "SeekBar",
            id = "sb_int_rate",
            layout_width = "fill",
            max = 100,
            progress = 50,
          },
          {
            "CheckBox",
            id = "cb_str_enc",
            text = "加密字符串 (<=1kb)",
            checked = true,
          },
          {
            "CheckBox",
            id = "cb_junk",
            text = "插入垃圾代码",
            checked = false,
          },
          {
            "TextView",
            text = "垃圾代码处理率",
            textSize = "12sp",
            layout_marginTop = "8dp",
          },
          {
            "SeekBar",
            id = "sb_junk_rate",
            layout_width = "fill",
            max = 100,
            progress = 20,
          },
          {
            "CheckBox",
            id = "cb_dep",
            text = "依赖自动识别",
            checked = true,
          },
        },
      },
      {
        "Button",
        id = "btn_obfuscate",
        layout_width = "fill",
        layout_height = "wrap",
        text = "开始混淆",
        backgroundColor = "#2196F3",
        textColor = "#FFFFFF",
      },
      {
        "ProgressBar",
        id = "prog_bar",
        layout_width = "wrap",
        layout_height = "wrap",
        layout_gravity = "center",
        visibility = "gone",
        layout_marginTop = "16dp",
      },
    },
  },
}

return layout
